name: eslint
on:
 push:
  branches:
  - main
env:
  TOKEN_WR_PACKAGE_REGISTRY: ${{ secrets.TOKEN_WR_PACKAGE_REGISTRY }}
jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Setup Node.js
     uses: actions/setup-node@v2
     with:
       node-version: '16'
   - name: Setup npmrc file and publish package
     run: |
       echo "@keybas-engineering:registry=https://npm.pkg.github.com" > .npmrc
       echo //npm.pkg.github.com/:_authToken=\"${{env.TOKEN_WR_PACKAGE_REGISTRY}}\" >> .npmrc
       npm install
       npm  publish
